In [2]:
# Importing NumPy Module
import numpy as np

### Creation of an array with step size 1.33 between 0 - 10

**arange() gives uncertain number of values based on steps**

In [16]:
print(np.arange(0, 10, 1.33, dtype=np.float32))

[0.        1.33      2.66      3.9900002 5.32      6.65      7.9800005
 9.31     ]


### Creation of an array with total 5 values between 0 - 160

**we use linspace(), which asks for total number of values**

In [22]:
print(np.linspace(0, 160, 5, dtype=np.float64))

[  0.  40.  80. 120. 160.]


# Reshaping Array

### Method I: Using array() and reshape() to convert array into matrix

In [23]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


### Method II: Using matrix() function
**NOTE: The np.matrix object is a legacy data structure. Its use is strongly discouraged in modern NumPy code. It behaves differently from NumPy arrays leading to confusing and inconsistent code. The professional standard is to use 2D np.ndarray for all matrix operations.**

In [26]:
print(np.matrix([[1,2,3],
                [5,6,8],
                [1,4,2]]))

[[1 2 3]
 [5 6 8]
 [1 4 2]]


### Method III: Using misc. functions

**Identity matrix**

In [27]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Zeros Matrix**

In [34]:
print(np.zeros((1,3)))

[[0. 0. 0.]]


**Ones Matrix**

In [36]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]
