In [17]:
# Importing NumPy Module 
import numpy as np

### 1. Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.

In [22]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**We use the np.diag((values), k=something) function which is used to construct a 2D array with a given 1D array on a specified diagonal.  
The k argument controls the offset.  
k=0 (default) for the main diagonal.  
k > 0 for diagonals above the main diagonal.  
k < 0 for diagonals below the main diagonal.  
NOTE: It creates a new 4×4-like matrix with 4, 5, 6 above the main diagonal -> but it doesn’t modify your existing arr.**

In [24]:
arr = np.diag((4,5,6), k=1)
print(arr)

[[0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]
 [0 0 0 0]]


### 2. Given a Numpy array arr1 = np.arange(11), negate all the elements between 6 and 10.

In [36]:
arr1 = np.arange(11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


**We use conditional masking method to do this.**

In [37]:
mask = ((arr1 >= 6) & (arr1 <= 10))
print(mask)

[False False False False False False  True  True  True  True  True]


In [38]:
print(arr1[mask])

[ 6  7  8  9 10]


**Now to Negate the Masked Values**

In [41]:
arr1[mask] = -(arr1[mask])
print(arr1)

[  0   1   2   3   4   5  -6  -7  -8  -9 -10]


### 3. Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.
```
import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
```
 


In [102]:
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
print(mat)
print(arr)

[['abc' 'A']
 ['def' 'B']
 ['ghi' 'C']
 ['jkl' 'D']]
['abc' 'dfe' 'ghi' 'kjl']


**Using a simple np.isin() funtion**

In [103]:
result = mat[np.isin(mat[:, 0], arr), 1]
print(result)

['A' 'C']


### 4. Given a matrix mat, sort it by the second column.
```
import numpy as np
mat1 = np.array([[1,21,3],[5,4,2],[56,12,4]])
```

In [66]:
mat1 = np.array([[1,21,3],[5,4,2],[56,12,4]])
print(mat1)

[[ 1 21  3]
 [ 5  4  2]
 [56 12  4]]


**Using np.argsort() function**

In [67]:
order = np.argsort(mat1[:,1])
mat1_sorted = mat1[order]
print(mat1_sorted)

[[ 5  4  2]
 [56 12  4]
 [ 1 21  3]]


### 5. Given an array arr, find the top 4 maximum values.
``` 
import numpy as np
arr2 = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
```

In [88]:
arr2 = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
print(arr2)

[ 90  14  24  13  13 590   0  45  16  50]


**Using argpartition()**

In [91]:
indices = np.argpartition(arr2, -4)[-4:]
print(indices)

[7 9 0 5]


In [92]:
top_4 = arr2[indices] 
print(np.sort(top_4))

[ 45  50  90 590]


### 6. Find the nearest number from the given number in an array.
```
arr3 = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50
```

In [93]:
arr3 = np.array([10,55,22,3,6,44,9,54])
print(arr3)

[10 55 22  3  6 44  9 54]


**First, we calculate the difference between each array element and the target number. Second, we take the absolute value of these differences to find the true distances. Finally, we use np.argmin() to get the index of the minimum distance, which allows us to retrieve the corresponding number from the original array.**

In [96]:
nearest_to = 50
abs_difference = np.abs(arr3 - nearest_to)
print(abs_difference)

[40  5 28 47 44  6 41  4]


In [98]:
min_dis = np.argmin(abs_difference)
print(min_dis)

7


In [100]:
result = arr3[min_dis]
print(result)

54
