#### Given a matrix mat of size 3 x 3. Find the maximum numbers from each row, say N1, N2 and N3. Result in a matrix by adding:  
``` 
import numpy as np
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)
```
**-N1 to the upper half elements of mat  
-N2 to the main diagonal elements of mat  
-N3 to the lower half elements of mat**

In [1]:
import numpy as np

In [2]:
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)
print(mat)

[[10  5  9]
 [ 2 20  6]
 [ 8  3 30]]


In [3]:
N1, N2, N3 = np.max(mat, axis=1)
print(N1, N2, N3)

10 20 30


In [4]:
upper = np.triu_indices(3, k=1)   # upper triangle (excluding diagonal)
lower = np.tril_indices(3, k=-1)  # lower triangle (excluding diagonal)
diag  = np.diag_indices(3)        # diagonal

In [5]:
print(upper)
print(lower)
print(diag)

(array([0, 0, 1]), array([1, 2, 2]))
(array([1, 2, 2]), array([0, 0, 1]))
(array([0, 1, 2]), array([0, 1, 2]))


In [6]:
res = mat.copy()
res[upper] += N1   # add N1 to upper half
res[diag]  += N2   # add N2 to diagonal
res[lower] += N3   # add N3 to lower half

In [10]:
print(res)

[[30 15 19]
 [32 40 16]
 [38 33 50]]
