# Linear Algebra Operations

## Numpy offers a separate module for linear algebra named linalg.

In [37]:
# Importing NumPy Module
import numpy as np

**Initializing Matrices**

In [38]:
# Matrix 1 with 4 elements and (2,2) dimension.
mat1 = np.arange(4).reshape(2,2)
print(mat1)

[[0 1]
 [2 3]]


In [39]:
# Matrix 2 with 4 elements with step = 2 and (2,2) dimension.
mat2 = (np.arange(4)*2).reshape(2,2)
print(mat2)

[[0 2]
 [4 6]]


In [40]:
# Matrix 3 with 4 elements with step = 3 and (2,2) dimension.
mat3 = (np.arange(4)*3).reshape(2,2)
print(mat3)

[[0 3]
 [6 9]]


## Performing multiple dot product in one go:

**Multiple dot product can be calculated just by passing the matrices as list into multi_dot function.**

In [41]:
dot_product  = np.linalg.multi_dot( [mat1, mat2, mat3] )
print(dot_product)

[[ 36  66]
 [132 234]]


## Consider a system of linear equation given below:

$$\begin{aligned} 3x + y &= 9 \\ x + 2y &= 8 \end{aligned}$$

**First we check if equation has a unique solution, if yes, we find inverse and rank of the matrix**

In [42]:
# Initializing matrices
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])

**Check if equation has unique solution.**

In [43]:
print(np.linalg.det(a))

5.000000000000001


In [44]:
# Since det = 5 which is non-zero. Hence, we have unique solutions Finding unique solution
print(np.linalg.solve(a, b))

[2. 3.]


In [45]:
# Calculating Inverse: Since, determinant is non-zero hence, matrix is invertible
print(np.linalg.inv(a))

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [46]:
# Calculating Rank of the matrix 
print(np.linalg.matrix_rank(a))

2
