# Exercise on Linear Algebra Calculations using NumPy

In [26]:
import numpy as np

### Q. 1  Solve the following system of linear equations.
$$
\begin{aligned} 2x + 3y + 2z &= 1 \\ x + 3z &= 2 \\ 2x + 2y + 3z &= 3 \end{aligned}
$$

In [27]:
a = np.array([[2, 3, 2], [1, 0, 3], [2, 2, 3]])
b = np.array([1, 2, 3])

In [28]:
solved = np.linalg.solve(a, b)
print(solved)

[11. -5. -3.]


### Q. 2 Multiply the following Matrices using methods available in numpy library.
$$
\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}
$$

In [29]:
mat1 = np.array([[1, 2, 3], [4, 5, 6]])
print(mat1)

[[1 2 3]
 [4 5 6]]


In [30]:
mat2 = np.array([7, 8, 9, 10, 11, 12]).reshape(3,2)
print(mat2)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [31]:
# Since number of columns in mat1 = number of rows in mat2. Therefore, Matrix multiplication is possible.
multi_mat = np.matmul(mat1, mat2)
print(multi_mat)

[[ 58  64]
 [139 154]]


### Q. 3 A system of linear equations is said to have a unique solution if the determinant of the co-efficient matrix is not Zero. Verify the existence of a unique solution for the following system of linear equations.
$$
\begin{aligned} -4x + 10y &= 6 \\ 2x - 5y &= 3 \end{aligned}
$$

In [32]:
mat_a = np.array([[-4, 10], [2, -5]])
print(mat_a)

[[-4 10]
 [ 2 -5]]


In [33]:
mat_b = np.array([6,3])
print(mat_b)

[6 3]


In [34]:
det = np.linalg.det(mat_a)
print(det)

0.0


**Since the determinant is 0, the system of linear equations does not have a unique solution.**